---
- name: Monitoring
  hosts: webservers
  gather_facts: no
  tasks:
    - name: Check for Docker Network
      command: docker network ls -q --filter 'name=prom'
      register: output
      changed_when: output.stdout == ''
    - debug:
        msg: "{{ output.stdout }}"
      when: output.stdout != ''
    - name: Create Docker Network
      command: docker network create --attachable prom
      when: output.stdout == ''
    - name: Deploy Node Exporter
      docker_container:
        name: node-exporter
        image: quay.io/prometheus/node-exporter
        command: --path.rootfs /host
        state: started
        restart_policy: unless-stopped
        networks:
          - name: prom
        pid_mode: host
        published_ports:
          - localhost:9100:9100
        volumes:
          - /:/host:ro,rslave
    - name: Create Prometheus Config Dir
      file:
        path: /etc/prometheus/
        state: directory
        owner: root
        group: root
        mode: 0775
    - name: Copy Prometheus Config
      copy:
        src: "monitoring_config/prometheus.yml"
        dest: "/etc/prometheus/prometheus.yml"
      register: prom_conf
    - name: Deploy Prometheus
      docker_container:
        name: prometheus
        image: prom/prometheus
        state: started
        command: --config.file=/etc/prometheus/prometheus.yml
        # Restart prometheus if/when the config file changes.
        restart: "{{ 'yes' if prom_conf.changed else 'no' }}"
        restart_policy: unless-stopped
        # TODO: Add a mount for prometheus data
        volumes:
          - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        networks:
          - name: prom
        published_ports:
          - localhost:9090:9090
    - name: Deploy Grafana
      docker_container:
        name: grafana
        image: grafana/grafana
        state: started
        env:
          GF_SERVER_DOMAIN: monitoring.tlkamp.com
          GF_AUTH_ANONYMOUS_ENABLED: "true"
          GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
          GF_AUTH_ANONYMOUS_ORG_NAME: "Main Org."
        restart_policy: unless-stopped
        networks:
          - name: prom
        published_ports:
          - localhost:3000:3000