---
- hosts: webservers
  gather_facts: no
  tasks:
    - name: apt updates
      apt:
        autoremove: yes
        upgrade: dist
        update_cache: yes
    - name: Ensure ufw is enabled
      ufw:
        state: enabled
    - name: Ensure services are installed
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - postgresql
    - name: Ensure gunicorn installed
      pip:
        name: gunicorn
        state: present
    - name: Ensure services are running
      systemd:
        state: started
        name: "{{ item }}"
        enabled: yes
      loop:
        - nginx
        - mygunicorn.service
        - postgresql
    - name: Ensure catalog user present
      user:
        name: catalog
        state: present
        shell: /usr/sbin/nologin